### ISSUE TITLE
Audio/Video Calls dont show up but text notifications do

### ISSUE THREAD

**Issue by radughitescu** [cometchat-pro-extensions/ios-swift-push-notifications-sample-app#2]
### Describe the problem

Using the example application, text messages sent to another user show up as notifications on that other user device, but Audio/Video Calls don't, **only when the app is opened** i see a sort of snackbar saying "Incoming call received".
When the app is closed, i get a notification when the call is missed, but again, nothing when to notify when the call is actually happening.
Keep in mind that i have not modified anything about the sample app except for the app keys and signing profiles.
Having text messages behave normally, with a push notification showing up even when the app is closed, i would assume my configuration of the project with the keys, signing profiles and the .p12 cert is correct

### What was the expected behavior?
Keeping in mind that this example app is using CallKit I was expecting calls to appear as any other call(example whatssapp/telegram calls).

### Reproduction

- Step 1: Configure the app (apple .p12 cer, enabled notifications with "Notify incoming calls" enabled and
"Notify missed call" enabled, cometchat app keys, signing profiles)
- Step 2: Close app on device 
- Step 3: Call Device A from Device B
- Step 4: Device A has not received any notification of the call

### Environment
The device that triggers the call is a simulator, the device that receives the call is a physical device

- **Version used:** Version: v3.0 Cometchat app and Token based(v2) Notification service from cometchat

**Comment by pushpsenairekar2911** [comment]
Hello @radughitescu, 
 
Can you please tell us which approach are you using for the push notifications i.e Firebase or APNS? 
Also, can you just confirm the certificate which you've created is includes VoIP push notification?

Also, to check the push notification configuration please keep the phone in the background and then check by sending the messages. If you were able to receive the notifications for messages then you should receive the notifications for calls as well. 

In case you missed something, please correct it via documentation: 
Using APNS: https://prodocs.cometchat.com/docs/ios-extensions-enhanced-push-notification-apns
Using Firebase: https://prodocs.cometchat.com/docs/ios-extensions-enhanced-push-notification


Regards, 
Pushpsen R. Airekar

**Comment by radughitescu** [comment]
I'm using APNS, i was able to fix this by regenerating the p12 certificate! So issue solved, i will close this.
